### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by jozephbrasil** [WHMCS/sample-gateway-module#7]
How to create custom fields on gateway module? My gateway (not link, but capture) ask per installments (number between 1 to 10), and I have no idea how to pass this information to gateway module to capture function.

**Comment by mclotfelter** [comment]
jozephbrasil... no one has answered your question because WHMCS isn't really trying to teach anyone how to develop custom modules. (real development info is actually very closely guarded)

In other words... they aren't really developer friendly

**Comment by jozephbrasil** [comment]
Yep! I know that... Thanks for your consolations!

**Comment by mattpugh** [comment]
Custom fields such as those offered for clients are products are not supported for gateway modules. You would have to script something custom in order to accommodate what you desire here.

FYI, Github issues are not actively monitored for support related questions. It would be better to submit questions such as these to our support desk in future.
